version: "2"
services:
    db:
        image: mongo:3.4.2
        environment:
            # enter credentials here
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD7
        volumes:
            - /data/db:/data/db
        ports:
            - "27017:27017"    
    api:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/reconfiu
            - /etc/localtime:/etc/localtime            
        links:
            - db

