version: "2"
services:
    db:
        image: mongo:3.0.14
        volumes:
            - /data/db:/data/db
        ports:
            - "27017:27017"    
    api:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/reconfiu
            - /etc/localtime:/etc/localtime            
        links:
            - db

